name: 'Run HLint'
description: 'Run hlint and format the output for a problem matcher'
inputs:
  hlint-bin:
    description: 'hlint binary path, if not already in PATH'
    required: false
  path:
    description: 'Path or JSON array of paths to check with hlint'
    required: true
    default: '.'
runs:
  using: 'node12'
  main: 'dist/index.js'
