name: "/setup"
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

defaults:
  run:
    working-directory: setup

jobs:
  test:
    name: Unit Tests - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: setup/package-lock.json
      - run: npm ci --prefer-offline --no-audit --progress=false
      - run: npm run bundle
      - run: npm test

  install-haskell:
    name: GHC ${{ matrix.ghc }}, Cabal ${{ matrix.cabal }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        # Try the latest version and the oldest "traditionally supported" versions
        ghc: ["latest", "9.0.2"]
        # Try the two most widely used versions of cabal
        cabal: ["latest", "3.6.2.0"]
        include:
          - os: ubuntu-latest
            # Try the latest GHC with an old version of cabal
            ghc: "latest"
            cabal: "2.4.0.1"
          - os: windows-latest
            # Try the a GHC that needed to be patched in chocolatey
            # (in chocolatey it's 8.10.2.2)
            ghc: "8.10.2"
            cabal: "latest"
          # Try the earliest version of GHC supported by ghcup.
          - os: ubuntu-latest
            ghc: "7.10.3"
            cabal: "3.6"
    steps:
      - uses: actions/checkout@v3
      - uses: ./setup
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - name: Test runghc
        run: |
          runghc --version
          runghc __tests__/hello.hs
      - name: Build test project
        working-directory: setup/__tests__/project
        run: cabal build
      - name: Run test project
        working-directory: setup/__tests__/project
        run: cabal run
      - name: Show installed versions
        run: |
          cabal --version
          ghc --version
      - name: Confirm installed and expected versions match
        shell: bash
        # this check depends on the ghc versions being "exact" in the matrix
        if: "matrix.ghc != 'latest'"
        # pure bash startsWith
        run: |
          [[ "${{ matrix.cabal }}" =~ ^([0-9]+\.[0-9]+)\. ]] && ver="${BASH_REMATCH[1]}"
          [[ "$(cabal --numeric-version)" =~ ^"$ver" ]]
          [[ "$(ghc --numeric-version)" == "${{ matrix.ghc }}" ]]

  test-fallback:
    name: Test GHC Installation Fallbacks - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: ./setup
        id: setup
        env:
          RUNNER_DEBUG: "1"
        with:
          ghc-version: 8.21.5
      - name: Error on success
        if: steps.setup.outputs.failed == 'true'
        run: |
          echo "Error: ghc 8.21.5 didn't fail to install"

  install-stack:
    name: Stack ${{ matrix.stack }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        # Test the latest stack version and a very old one
        stack: ["latest", "1.9.1"]

    steps:
      - uses: actions/checkout@v3
      - uses: ./setup
        with:
          enable-stack: true
          stack-no-global: true
          stack-version: ${{ matrix.stack }}
      - run: |
          stack --version
          stack --help
